#!/usr/bin/env bash
# Shared plumbing for every script in this brain. Sourced, never executed.
#
# Three jobs:
#   1. Resolve BRAIN_DIR and export GBRAIN_HOME so this brain is isolated from
#      every other brain on the machine (gbrain appends '.gbrain' to
#      GBRAIN_HOME itself, and rejects relative paths or '..' segments).
#   2. Load brain.conf and fail loudly when it is missing or half-filled.
#   3. Parse sources.manifest / sparse-excludes with validation, because a
#      space where a tab belongs is the single most common way to break a
#      brain and the failure is otherwise silent.

set -euo pipefail

# ---------------------------------------------------------------- paths ----

# pwd -P: GBRAIN_HOME must be absolute with no '..' segments or gbrain throws.
BRAIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
export BRAIN_DIR

CONF="$BRAIN_DIR/brain.conf"
MANIFEST="$BRAIN_DIR/sources.manifest"
SPARSE="$BRAIN_DIR/sparse-excludes"
CLONES_DIR="$BRAIN_DIR/sources"
INBOX_DIR="$BRAIN_DIR/inbox"

# This is the whole multi-brain story: every gbrain invocation from this repo
# reads and writes <repo>/.gbrain instead of ~/.gbrain, so N brains coexist.
export GBRAIN_HOME="$BRAIN_DIR"
GBRAIN_CONFIG_DIR="$BRAIN_DIR/.gbrain"

# --------------------------------------------------------------- output ----

if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_DIM=$'\033[2m'; C_RED=$'\033[31m'
  C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_BOLD=$'\033[1m'
else
  C_RESET=''; C_DIM=''; C_RED=''; C_GREEN=''; C_YELLOW=''; C_BOLD=''
fi

log()  { printf '%s==>%s %s\n' "$C_BOLD" "$C_RESET" "$*"; }
info() { printf '    %s\n' "$*"; }
dim()  { printf '%s    %s%s\n' "$C_DIM" "$*" "$C_RESET"; }
ok()   { printf '%s  ok%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn() { printf '%s  !!%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
die()  { printf '%s ERR%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 1; }

# ---------------------------------------------------------------- config ----

load_conf() {
  # Secrets first, so brain.conf's ${VAR:=default} assignments see them and the
  # environment keeps winning. This file is gitignored and is the ONLY place in
  # a local install where an API key belongs — brain.conf is committed.
  if [[ -f "$BRAIN_DIR/.env" ]]; then
    local perms
    perms=$(stat -f '%Lp' "$BRAIN_DIR/.env" 2>/dev/null || stat -c '%a' "$BRAIN_DIR/.env" 2>/dev/null || echo '')
    [[ -n "$perms" && "$perms" != "600" && "$perms" != "400" ]] \
      && warn ".env is mode $perms — it holds API keys; chmod 600 .env"
    set -a
    # shellcheck disable=SC1091
    source "$BRAIN_DIR/.env"
    set +a
  fi

  [[ -f "$CONF" ]] || die "no brain.conf — run scripts/init.sh first"
  # shellcheck disable=SC1090
  source "$CONF"

  local missing=()
  for v in BRAIN_ID PG_PORT PG_DB PG_USER EMBED_PROFILE EMBED_MODEL EMBED_DIMS GBRAIN_PIN; do
    [[ -n "${!v:-}" ]] || missing+=("$v")
  done
  (( ${#missing[@]} == 0 )) || die "brain.conf is missing: ${missing[*]}"

  [[ "$BRAIN_ID" =~ ^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$ ]] \
    || die "BRAIN_ID '$BRAIN_ID' is invalid — gbrain source ids are [a-z0-9-], 2-32 chars"

  RERANKER="${RERANKER:-none}"
  RERANK_PORT="${RERANK_PORT:-8081}"
  PGDATA="${PGDATA:-$BRAIN_DIR/db/pg}"
  export PGDATA

  # Private repositories over HTTPS. On your own machine git already has a
  # credential helper; a container has nothing, so cloning a private repo fails
  # with an authentication prompt it cannot answer.
  #
  # GITHUB_TOKEN (a PAT with `repo` read, or `gh auth token`) rewrites
  # github.com HTTPS URLs to carry it. Nothing is written to disk and the
  # manifest keeps clean, committable URLs.
  #
  # Trade-off worth knowing: the token lands in this process's environment, so
  # it is visible to anyone who can read /proc for it. Fine on a laptop and in
  # a single-tenant container; on a shared host prefer a mounted credentials
  # file (see deploy/README.md) or SSH URLs with a deploy key.
  if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    export GIT_CONFIG_COUNT=1
    export GIT_CONFIG_KEY_0="url.https://x-access-token:${GITHUB_TOKEN}@github.com/.insteadOf"
    export GIT_CONFIG_VALUE_0="https://github.com/"
  fi

  # Where Postgres lives, and who owns its lifecycle.
  #   PG_MANAGED=1  this brain owns a dedicated cluster in db/pg and starts it
  #                 on demand (the local default)
  #   PG_MANAGED=0  Postgres is somebody else's problem — a container, a
  #                 managed service — and we only wait for it to answer
  PG_HOST="${PG_HOST:-127.0.0.1}"
  PG_MANAGED="${PG_MANAGED:-1}"
}

# Password lives outside git. Generated by bootstrap.sh locally; injected from
# the environment on a server, where it belongs to the secret store and not to
# a file in the brain directory.
pg_password() {
  if [[ -n "${PG_PASSWORD:-}" ]]; then printf '%s' "$PG_PASSWORD"; return; fi
  local f="$BRAIN_DIR/db/.pg-password"
  [[ -f "$f" ]] || die "no db/.pg-password and PG_PASSWORD is unset — run scripts/bootstrap.sh"
  tr -d '\n' < "$f"
}

database_url() {
  printf 'postgres://%s:%s@%s:%s/%s' \
    "$PG_USER" "$(pg_password)" "$PG_HOST" "$PG_PORT" "$PG_DB"
}

# ------------------------------------------------------------- postgres ----

# Homebrew keg-only installs are not on PATH; look there before giving up.
pg_bin_dir() {
  if [[ -n "${PG_BIN_DIR:-}" ]]; then printf '%s' "$PG_BIN_DIR"; return; fi
  local candidates=(
    /opt/homebrew/opt/postgresql@17/bin
    /usr/local/opt/postgresql@17/bin
    /usr/lib/postgresql/17/bin
  )
  local d
  for d in "${candidates[@]}"; do
    [[ -x "$d/pg_ctl" ]] && { printf '%s' "$d"; return; }
  done
  command -v pg_ctl >/dev/null 2>&1 && { printf '%s' "$(dirname "$(command -v pg_ctl)")"; return; }
  die "postgresql 17 not found — install it (macOS: brew install postgresql@17 pgvector) or set PG_BIN_DIR in brain.conf"
}

pg_running() {
  if command -v pg_isready >/dev/null 2>&1; then
    pg_isready -h "$PG_HOST" -p "$PG_PORT" -q >/dev/null 2>&1
  else
    "$(pg_bin_dir)/pg_isready" -h "$PG_HOST" -p "$PG_PORT" -q >/dev/null 2>&1
  fi
}

# Lazy start. Nothing in this template runs at boot; the MCP wrapper and the
# scripts start the cluster on first use and leave it up. When Postgres is not
# ours (PG_MANAGED=0) we wait rather than start.
pg_ensure_running() {
  pg_running && return 0

  local i
  if [[ "$PG_MANAGED" != "1" ]]; then
    for i in $(seq 1 30); do
      pg_running && return 0
      sleep 1
    done
    die "postgres at $PG_HOST:$PG_PORT is not answering"
  fi

  [[ -d "$PGDATA" ]] || die "no cluster at $PGDATA — run scripts/bootstrap.sh"
  "$(pg_bin_dir)/pg_ctl" -D "$PGDATA" -l "$PGDATA/server.log" start >/dev/null 2>&1 || true
  for i in $(seq 1 15); do
    pg_running && return 0
    sleep 1
  done
  die "postgres did not come up on :$PG_PORT — see $PGDATA/server.log"
}

psql_brain() {
  local psql_bin
  if command -v psql >/dev/null 2>&1; then psql_bin=psql; else psql_bin="$(pg_bin_dir)/psql"; fi
  PGPASSWORD="$(pg_password)" "$psql_bin" \
    -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" -d "$PG_DB" "$@"
}

# ------------------------------------------------------------- reranker ----

# /health returns ok BEFORE the model finishes loading, and gbrain queries
# against a half-loaded reranker silently return "No results". Probe with a
# real rerank call or don't probe at all.
reranker_ready() {
  curl -s -m 2 "http://127.0.0.1:$RERANK_PORT/v1/rerank" \
    -H 'Content-Type: application/json' \
    -d '{"query":"x","documents":["y"]}' 2>/dev/null | grep -q relevance_score
}

# -------------------------------------------------------------- manifest ----

# Emits validated rows, always normalized to 5 tab-separated fields
# (id, url, branch, strategy, visibility) so callers can read a fixed shape.
#
# Dies on a row that is not 4 or 5 tab-separated fields — usually someone typed
# spaces, which would otherwise be read as an id containing the whole line — and
# on a duplicate id, which is worse than it looks: two rows sharing an id map to
# the same clone directory, so every bootstrap would "rebranch" the clone back
# and forth and every refresh would re-import the whole source.
manifest_rows() {
  [[ -f "$MANIFEST" ]] || die "no sources.manifest — run scripts/init.sh first"
  local lineno=0 line seen=""
  while IFS= read -r line || [[ -n "$line" ]]; do
    lineno=$((lineno + 1))
    [[ "$line" =~ ^[[:space:]]*(#.*)?$ ]] && continue

    local fields; fields=$(awk -F'\t' '{print NF}' <<<"$line")
    if [[ "$fields" -ne 4 && "$fields" -ne 5 ]]; then
      die "sources.manifest line $lineno has $fields tab-separated field(s), expected 4 or 5
    (id⇥url⇥branch⇥strategy[⇥federated|isolated]). Tabs, not spaces:
    $line"
    fi

    local id strategy visibility
    id=$(cut -f1 <<<"$line")
    strategy=$(cut -f4 <<<"$line")
    visibility=$([[ "$fields" -eq 5 ]] && cut -f5 <<<"$line" || echo federated)

    [[ "$id" =~ ^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$ ]] \
      || die "sources.manifest line $lineno: invalid source id '$id' — 2-32 chars of [a-z0-9-]"

    if grep -qxF "$id" <<<"$seen"; then
      die "sources.manifest line $lineno: duplicate source id '$id'.
    Two rows cannot share an id — they would share a clone directory and fight
    over its branch. To index two branches of one repo, give each its own id:
      api-v1⇥<url>⇥release/v1⇥code
      api-v2⇥<url>⇥main⇥code"
    fi
    seen+="$id"$'\n'

    case "$strategy" in
      code|markdown|auto) ;;
      *) die "sources.manifest line $lineno: unknown strategy '$strategy' (code|markdown|auto)" ;;
    esac
    case "$visibility" in
      federated|isolated) ;;
      *) die "sources.manifest line $lineno: unknown visibility '$visibility' (federated|isolated)" ;;
    esac

    printf '%s\t%s\t%s\t%s\t%s\n' \
      "$id" "$(cut -f2 <<<"$line")" "$(cut -f3 <<<"$line")" "$strategy" "$visibility"
  done < "$MANIFEST"
}

manifest_ids() { manifest_rows | cut -f1; }

# Paths excluded per source, for git sparse-checkout.
sparse_ids() {
  [[ -f "$SPARSE" ]] || return 0
  grep -v '^[[:space:]]*#' "$SPARSE" | awk -F'\t' 'NF>=2 && $1!="" {print $1}' | sort -u
}

sparse_paths_for() {
  [[ -f "$SPARSE" ]] || return 0
  grep -v '^[[:space:]]*#' "$SPARSE" | awk -F'\t' -v id="$1" 'NF>=2 && $1==id {print $2}'
}

# ----------------------------------------------------------------- misc ----

need() { command -v "$1" >/dev/null 2>&1 || die "$1 not found on PATH${2:+ — $2}"; }

# First free TCP port at or after $1. Used by init.sh so a second brain on the
# same machine does not collide with the first.
port_in_use() {
  if command -v nc >/dev/null 2>&1; then
    nc -z 127.0.0.1 "$1" >/dev/null 2>&1
  else
    # bash's own TCP redirection — no external dependency. Without this a
    # machine lacking nc would silently hand every brain the same port.
    (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
  fi
}

free_port_from() {
  local p="$1" tries=0
  while port_in_use "$p" && (( tries < 200 )); do
    p=$((p + 1)); tries=$((tries + 1))
  done
  printf '%s' "$p"
}

confirm() {
  local prompt="$1"
  [[ "${ASSUME_YES:-0}" == "1" ]] && return 0
  local reply
  read -r -p "$prompt [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]]
}
